kumuluzee:
  name: image-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    websocket:
      enabled: true
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql://host.docker.internal:5432/image-metadata
      username: dbuser
      password: postgres
      pool:
        max-size: 4
  dev:
    scan-libraries:
      - image-catalog-models
      - image-catalog-services
      - image-catalog-lib
  websocket:
    enabled: true
  openapi-mp:
    ui:
      specification-server: http://20.246.105.245:8080

  health:
    checks:
      #data-source-health-check:
      #  type: liveness
      #  jndi-name: jdbc/ImageMetadataDS
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  #metrics:
  #  web-instrumentation:
  #    - name: images-endpoint
  #      url-pattern: /v1/images/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <File name="dmcreator" fileName="logs/dmcreator.log">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </File>
                                    <!-- File Appender for WebSocket and Jetty Logs -->
                                    <File name="websocketFile" fileName="logs/websocket-logs.log">
                                      <PatternLayout pattern="%d [%t] %-5level %logger{36} - %msg%n"/>
                                    </File>    
                                </Appenders>
                                <Loggers>
                                  <!-- General Logs -->
                                  <Root level="info">
                                    <AppenderRef ref="console" />
                                  </Root>
                                  <!-- Logger for Jetty -->
                                  <Logger name="org.eclipse.jetty" level="DEBUG" additivity="false">
                                    <AppenderRef ref="websocketFile"/>
                                  </Logger>
                                  <!-- Logger for WebSocket -->
                                  <Logger name="jakarta.websocket" level="DEBUG" additivity="false">
                                    <AppenderRef ref="websocketFile"/>
                                  </Logger>
                              </Loggers>
                            </Configuration>'
rest-properties:
  broken: false
app-properties:
  amazon-rekognition:
    access-key:
    secret-key:

