INSERT INTO image_metadata (title, description, width, height, created, uri) VALUES ('Our first image', 'This is the first image that we created for the RSO course.', 1280, 1325, TIMESTAMP '2006-01-01 15:36:38', 'https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails/image/tess_first_light-tb.jpg');
INSERT INTO image_metadata (title, description, width, height, created, uri) VALUES ('Our second image', 'This is the second image that we created for the RSO course.', 1280, 1325, TIMESTAMP '2006-01-01 15:36:38', 'https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails/image/tess_first_light-tb.jpg');
INSERT INTO image_metadata (title, description, width, height, created, uri) VALUES ('Our third image', 'This is the third image that we created for the RSO course.', 1280, 1325, TIMESTAMP '2006-01-01 15:36:38', 'https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails/image/tess_first_light-tb.jpg');
INSERT INTO image_metadata (title, description, width, height, created, uri) VALUES ('Our fourth image','This is the fourth image that we created for the RSO course.',1280,1325,TIMESTAMP '2006-01-01 15:36:38','https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails/image/tess_first_light-tb.jpg');

INSERT INTO dms (name, description, created, user_id)  VALUES ('Dungeon Master 1', 'Default DM for testing purposes', CURRENT_TIMESTAMP, 'user123');
INSERT INTO boats (title, description, width, height, created, crew, str, dex, cha, intelligence, wis, charisma, armorclass, hpHull, hpSails, hpSteer, dm_id)  VALUES ('Airship', 'Gargantuan vehicle (80 ft. by 20 ft.). Creature capacity: 20 crew, 10 passengers. Cargo capacity: 1 ton. Travel pace: 9 miles per hour (216 miles per day).', 80, 20, CURRENT_TIMESTAMP, 20, 14, 14, 0, 0, 0, 0, 13, 300, 100, 50, 1);
INSERT INTO boats (title, description, width, height, created, crew, str, dex, cha, intelligence, wis, charisma, armorclass, hpHull, hpSails, hpSteer, dm_id)  VALUES ('Galley', 'Gargantuan vehicle (130 ft. by 20 ft.). Creature capacity: 80 crew, 40 passengers. Cargo capacity: 150 tons. Travel pace: 4 miles per hour (96 miles per day).', 130, 20, CURRENT_TIMESTAMP, 80, 24, 4, 0, 0, 0, 0, 15, 500, 100, 50, 1);
INSERT INTO boats (title, description, width, height, created, crew, str, dex, cha, intelligence, wis, charisma, armorclass, hpHull, hpSails, hpSteer, dm_id)  VALUES ('Keelboat', 'Gargantuan vehicle (60 ft. by 20 ft.). Creature capacity: 3 crew, 4 passengers. Cargo capacity: 0.5 tons. Travel pace: 3 miles per hour (72 miles per day).', 60, 20, CURRENT_TIMESTAMP, 3, 16, 7, 0, 0, 0, 0, 15, 100, 100, 50, 1);
INSERT INTO boats (title, description, width, height, created, crew, str, dex, cha, intelligence, wis, charisma, armorclass, hpHull, hpSails, hpSteer, dm_id)  VALUES ('Longship', 'Gargantuan vehicle (70 ft. by 20 ft.). Creature capacity: 40 crew, 100 passengers. Cargo capacity: 10 tons. Travel pace: 5 miles per hour (120 miles per day).', 70, 20, CURRENT_TIMESTAMP, 40, 20, 6, 0, 0, 0, 0, 15, 300, 100, 50, 1);
INSERT INTO boats (title, description, width, height, created, crew, str, dex, cha, intelligence, wis, charisma, armorclass, hpHull, hpSails, hpSteer, dm_id)  VALUES ('Rowboat', 'Large vehicle (10 ft. by 5 ft.). Creature capacity: 2 crew, 2 passengers. Cargo capacity: 0.25 tons. Travel pace: 3 miles per hour (24 miles per day).', 10, 5, CURRENT_TIMESTAMP, 2, 11, 8, 0, 0, 0, 0, 11, 50, 25, 25, 1);
INSERT INTO boats (title, description, width, height, created, crew, str, dex, cha, intelligence, wis, charisma, armorclass, hpHull, hpSails, hpSteer, dm_id)  VALUES ('Sailing Ship', 'Gargantuan vehicle (80 ft. by 20 ft.). Creature capacity: 30 crew, 20 passengers. Cargo capacity: 100 tons. Travel pace: 5 miles per hour (120 miles per day).', 80, 20, CURRENT_TIMESTAMP, 30, 20, 7, 0, 0, 0, 0, 15, 300, 100, 50, 1);
INSERT INTO boats (title, description, width, height, created, crew, str, dex, cha, intelligence, wis, charisma, armorclass, hpHull, hpSails, hpSteer, dm_id)  VALUES ('Warship', 'Gargantuan vehicle (100 ft. by 20 ft.). Creature capacity: 40 crew, 60 passengers. Cargo capacity: 200 tons. Travel pace: 4 miles per hour (96 miles per day).', 100, 20, CURRENT_TIMESTAMP, 40, 20, 4, 0, 0, 0, 0, 15, 500, 100, 50, 1);


